### ISSUE TITLE
Extraneous characters in output

### ISSUE THREAD

**Issue by sdwfrost** [Calysto/scilab_kernel#10]
In addition to the lack of syntax highlighting, there is also an issue with the output being spooled; see [http://epirecip.es/epicookbook/chapters/blackross2015/scilab](http://epirecip.es/epicookbook/chapters/blackross2015/scilab).

**Comment by tanchinluh** [comment]
Suggestion to slightly modified the "Print" code for the kernel:

def Print(self, text):
    text = text.strip('\x1b[0m')
    if text and (str(text)!=' \x08'):
        super(ScilabKernel, self).Print(text)

Tested on Scilab 6 kernel window and linux

**Comment by blink1073** [comment]
Thanks for the tip, @tanchinluh!  Fixed in 0.9.8.
