### ISSUE TITLE
Kernel dies/fails to connect on Windows with Scilab 6.0.1

### ISSUE THREAD

**Issue by mobius-eng** [Calysto/scilab_kernel#11]
On Windows there is no `scilab-adv-cli`, so I tried setting `SCILAB_EXECUTABLE` to `C:\Path\To\Scilab\bin\scilab.bat` or to `C:\Path\To\Scilab\bin\scilab.bat -nw` (`-nw` option must have similar effect of `scilab-adv-cli` on MacOS and Linux): Scilab starts (with a visible window without `-nw` option), but Jupyter doesn't connect to it.

**Comment by blink1073** [comment]
Hi @mobius-eng, I plan to add support for Scilab 6.0 next week.
