### ISSUE TITLE
Scilab kernel always timeout

### ISSUE THREAD

**Issue by New1997** [Calysto/scilab_kernel#13]
I can't use scilab with jupyter because it always timeout and won't execute the code

**Comment by blink1073** [comment]
Hi @New1997, which operating system and which version of Scilab are you using?

**Comment by New1997** [comment]
ubuntu 18.04
scilab 6.0.1
sorry for not being specific earlier

**Comment by blink1073** [comment]
I am using a similar setup.  Did you set the `SCILAB_EXECUTABLE`?  I have `export SCILAB_EXECUTABLE=~/scilab-6.0.2/bin/scilab-cli` in my `~/.bashrc`.

**Comment by New1997** [comment]
i use `export SCILAB_EXECUTABLE=/usr/bin/scilab-adv-cli` but still the same, the kernel timeout

**Comment by New1997** [comment]
whenever I start the kernel (open a notebook) I got this `Timeout waiting for kernel_info reply` after `Kernel started`

**Comment by blink1073** [comment]
Let's try a low level approach, please launch python and try the following:

```python
from scilab_kernel.kernel import ScilabKernel   
wrapper = ScilabKernel().makeWrapper() 
print(wrapper.run_command("ones('3')"))
```

On my machine that prints:

```
 ans  =

   1.
```

**Comment by New1997** [comment]
I got `No module named 'scilab_kernel'`

**Comment by blink1073** [comment]
Can you please do the following:

```bash
jupyter kernelspec list
cat <path_to_scilab_kernel>/kernel.json
```

And try with the python given in "argv"?

**Comment by New1997** [comment]
same output

**Comment by blink1073** [comment]
What was the path in `argv`?

**Comment by New1997** [comment]
what do you mean?

**Comment by blink1073** [comment]
I meant what was the python path the kernel was expecting to use.

**Comment by blink1073** [comment]
e.g. `/home/silvester/miniconda3/bin/python`

**Comment by New1997** [comment]
`/usr/local/share/jupyter/kernels/scilab/kernel.json`

**Comment by blink1073** [comment]
can you please give the contents of that file?

**Comment by New1997** [comment]
any luck?

**Comment by blink1073** [comment]
Please try `jupyter kernelspec remove scilab` and then `pip install scilab_kernel`, and then paste the contents of that file again.

**Comment by New1997** [comment]
`{
    "argv": ["python",
             "-m", "scilab_kernel",
             "-f", "{connection_file}"],
    "display_name": "Scilab",
    "language": "scilab",
    "mimetype": "text/x-octave",
    "name": "scilab"
}
`

**Comment by blink1073** [comment]
Does `python -c "import scilab_kernel"` work now?

**Comment by New1997** [comment]
the thing is I can't even do 
`from scilab_kernel.kernel import ScilabKernel`
in python

**Comment by blink1073** [comment]
Okay, what is `which python`, `which pip`?

**Comment by New1997** [comment]
first i install with pip3
but now i launch python 2.7

**Comment by New1997** [comment]
no it is okay, I see, It use miniconda python instead of global python

**Comment by blink1073** [comment]
It uses whichever is first in your $PATH

**Comment by New1997** [comment]
how to fix it ?
btw i tried 
`from scilab_kernel.kernel import ScilabKernel`
`wrapper = ScilabKernel().makeWrapper()`
`print(wrapper.run_command("ones('3')"))`

with python from `/usr/bin` (I kind of using it raw for test)
and it got stuck at `wrapper = ScilabKernel().makeWrapper()`

**Comment by blink1073** [comment]
It just hangs?

**Comment by New1997** [comment]
yes

**Comment by blink1073** [comment]
Do you have a scilab startup file?  https://help.scilab.org/docs/5.3.3/en_US/startup.html

**Comment by New1997** [comment]
I will git you the output of `ls .Scilab/scilab-6.0.1/` 
`atoms 
history
scinotesConfiguration.xml
XConfiguration.xml
configuration.xml
palettes.xml
WindowsConfiguration.xml
xcos.xml
`

**Comment by New1997** [comment]
so?

**Comment by blink1073** [comment]
When you start scilab-cli from the command line, does it print `-->` as the prompt?

**Comment by New1997** [comment]
No

**Comment by New1997** [comment]
and ```
scilab-adv-cli 
Picked up _JAVA_OPTIONS: -Djava.class.path=/usr/share/java/flexdock.jar:/usr/share/java/skinlf.jar:/usr/share/java/looks.jar:/usr/share/java/commons-logging.jar:/usr/share/java/jhall.jar:/usr/share/java/lucene-core-4.10.4.jar:/usr/share/java/lucene-analyzers-common-4.10.4.jar:/usr/share/java/lucene-queryparser-4.10.4.jar:/usr/share/maven-repo/org/freehep/freehep-util/debian/freehep-util-debian.jar:/usr/share/maven-repo/org/freehep/freehep-io/debian/freehep-io-debian.jar:/usr/share/maven-repo/org/freehep/freehep-graphicsio/debian/freehep-graphicsio-debian.jar:/usr/share/java/freehep-graphicsio-emf-2.1.jar:/usr/share/java/freehep-graphics2d-2.1.1.jar:/usr/share/java/jrosetta-API.jar:/usr/share/java/jrosetta-engine-1.0.4.jar:/usr/share/java/jgraphx.jar:/usr/share/java/jogl2.jar:/usr/share/java/gluegen2-rt.jar:/usr/share/java/jeuclid-core.jar:/usr/share/java/jlatexmath-fop-1.0.7.jar:/usr/share/java/fop.jar:/usr/share/java/saxon.jar:/usr/share/java/batik.jar:/usr/share/java/xml-apis-ext.jar:/usr/share/java/commons-io.jar:/usr/share/java/xmlgraphics-commons.jar:/usr/share/java/avalon-framework.jar:/usr/share/java/jlatexmath-1.0.7.jar:/usr/share/java/ecj.jar:/usr/share/java/javax.activation.jar:/usr/share/java/jaxb-runtime.jar:/usr/share/scilab/modules/commons/jar/org.scilab.modules.commons.jar:/usr/share/scilab/modules/gui/jar/org.scilab.modules.gui.jar:/usr/share/scilab/modules/xcos/jar/org.scilab.modules.xcos.jar:/usr/share/scilab/modules/history_browser/jar/org.scilab.modules.history_browser.jar:/usr/share/scilab/modules/ui_data/jar/org.scilab.modules.ui_data.jar:/usr/share/scilab/modules/external_objects_java/jar/org.scilab.modules.external_objects_java.jar:/usr/share/scilab/modules/jvm/jar/org.scilab.modules.jvm.jar:/usr/share/scilab/modules/preferences/jar/org.scilab.modules.preferences.jar:/usr/share/scilab/modules/core/jar/org.scilab.modules.core.jar:/usr/share/scilab/modules/scinotes/jar/org.scilab.modules.scinotes.jar:/usr/share/scilab/modules/graphic_export/jar/org.scilab.modules.graphic_export.jar:/usr/share/scilab/modules/types/jar/org.scilab.modules.types.jar:/usr/share/scilab/modules/scirenderer/jar/scirenderer.jar:/usr/share/scilab/modules/graphic_objects/jar/org.scilab.modules.graphic_objects.jar:/usr/share/scilab/modules/renderer/jar/org.scilab.modules.renderer.jar:/usr/share/scilab/modules/helptools/jar/org.scilab.modules.helptools.jar:/usr/share/scilab/modules/helptools/jar/scilab_images.jar:/usr/share/scilab/modules/helptools/jar/scilab_ru_RU_help.jar:/usr/share/scilab/modules/helptools/jar/scilab_en_US_help.jar:/usr/share/scilab/modules/localization/jar/org.scilab.modules.localization.jar:/usr/share/scilab/modules/console/jar/org.scilab.modules.console.jar:/usr/share/scilab/modules/completion/jar/org.scilab.modules.completion.jar:/usr/share/scilab/modules/action_binding/jar/org.scilab.modules.action_binding.jar:/usr/share/scilab/modules/graph/jar/org.scilab.modules.graph.jar:/usr/share/scilab/modules/javasci/jar/org.scilab.modules.javasci.jar:/usr/share/scilab/modules/history_manager/jar/org.scilab.modules.history_manager.jar:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.scilab.modules.jvm.LibraryPath (file:/usr/share/scilab/modules/jvm/jar/org.scilab.modules.jvm.jar) to field java.lang.ClassLoader.sys_paths
WARNING: Please consider reporting this to the maintainers of org.scilab.modules.jvm.LibraryPath
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
commons module not found.
graphic_objects module not found.
ui_data module not found.
graph module not found.
history_browser module not found.
slint module not found.
coverage module not found.
```

**Comment by New1997** [comment]
Do I need to purge all and install manually from scilab official page? (This one is the ubuntu from apt-get so I can't even use ATOMS)

**Comment by blink1073** [comment]
Are you able to interact with that session?  If so, what does `disp(prompt())` show?

**Comment by New1997** [comment]
Nothing

**Comment by blink1073** [comment]
Yeah, something is corrupt then.  Getting a working version of Scilab that shows that prompt is apparently the entry point :smile:

**Comment by New1997** [comment]
I can interact with it but it won't show any results but when using scilab-adv-cli I cant use plot or surf and it create a new graphic window without any problem

**Comment by New1997** [comment]
It only happens when I attempt to install scilab_kernel using python pip for the first time then even if I pruge everything it stays the same

**Comment by blink1073** [comment]
Hmm, maybe try with the adv-cli with a fresh install?

**Comment by New1997** [comment]
I think I will install using the package directly from scilab,
I will purge everything for now
Then I will comeback

**Comment by blink1073** [comment]
oh I see, you did that

**Comment by blink1073** [comment]
I'm not sure, we're just sending commands for scilab to run and waiting for `-->` to come back.

**Comment by New1997** [comment]
when using in cli or adv-cli the terminal went dead only the gui version works

**Comment by blink1073** [comment]
I'm curious if you can plot from adv-cli from a fresh install

**Comment by New1997** [comment]
I download scilab6.0.2.gz and extract the files
Everything works fine including scilab-adv-cli, it show plot, so how to make jupyter recongnize the kernel?

**Comment by New1997** [comment]
I don't know why but it takes too much time, then it hangs

**Comment by New1997** [comment]
ok, the question earlier says a lot about me (I am newbie) and it was answer earlier: `export SCILAB_EXECUTABLE=~/scilab-6.0.2/bin/scilab-cli` in `~/.bashrc`

**Comment by blink1073** [comment]
so with that variable defined, does the kernel start now?

**Comment by New1997** [comment]
yep thanks, you can close the ticket

**Comment by blink1073** [comment]
Great, glad you got sorted!

**Comment by ordonezt** [comment]
Hi! I'm having an similar issue.
I'm using Scilab 6.1.0, Jupyter-Notebook 6.0.1, IPython 7.8.0

I tried `pip install scilab_kernel`
Set the `export SCILAB_EXECUTABLE=/scilab-6.1.0/bin/scilab-adv-cli` in `/home/.bashrc` editing it with nano

If i run `echo $SCILAB_EXECUTABLE` i get:
`/home/ord/scilab-6.1.0/bin/scilab-adv-cli`

But when i run `ipython notebook` and open a scilab notebook i get:

> [I 13:25:12.924 NotebookApp] Kernel started: bd817fea-fb54-46d4-b62b-7d1d4fd6beaa
> [MetaKernelApp] ERROR | Exception in message handler:
> Traceback (most recent call last):
>   File "/home/ord/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
>     yield gen.maybe_future(handler(stream, idents, msg))
>   File "/home/ord/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 655, in kernel_info_request
>     content.update(self.kernel_info)
>   File "/home/ord/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 649, in kernel_info
>     'banner': self.banner,
>   File "/home/ord/anaconda3/lib/python3.7/site-packages/scilab_kernel/kernel.py", line 78, in banner
>     call = '%s -version -nwni || true' % self.executable
>   File "/home/ord/anaconda3/lib/python3.7/site-packages/scilab_kernel/kernel.py", line 69, in executable
>     raise OSError(msg)
> OSError: Scilab Executable not found, please add to path or set"SCILAB_EXECUTABLE" environment variable

Also if i run `python -m scilab_kernel.check` i get:

> Scilab kernel v0.9.10
> Metakernel v0.24.3
> Python v3.7.4 (default, Aug 13 2019, 20:35:49) 
> [GCC 7.3.0]
> Python path: /home/ord/anaconda3/bin/python
> 
> Connecting to Scilab...
> Scilab connection established
> Scilab Executable not found, please add to path or set"SCILAB_EXECUTABLE" environment variable

**Comment by blink1073** [comment]
Hi @New1997, I think the issue is that the [which](https://github.com/Calysto/metakernel/blob/7839576adb7661bbd3b4bc81881a8fc4f20dbcd3/metakernel/pexpect.py#L60) function is not seeing that file as executable.  You can verify in ipython:

```python
import os
from metakernel.pexpect import which
which(os.environ('SCILAB_EXECUTABLE')
```

**Comment by ordonezt** [comment]
Yes! Thank you, it's fixed now but i don't like my solution.

The problem was that i followed the instructions in this [video](https://www.youtube.com/watch?v=l8DXCGNcYHE) to make an "executable icon" of Scilab and Xcos, that makes me move the Scilab files (`/scilab-6.1.0`) to `/opt` folder.

Then i made the `SCILAB_EXECUTABLE` variable like this:
`export SCILAB_EXECUTABLE=opt/scilab-6.1.0/bin/scilab-adv-cli`

Then i run:
`import os`
`from metakernel.pexpect import which`
`which(os.environ['SCILAB_EXECUTABLE'])`
And i get nothing

But if i move the Scilab files (`/scilab-6.1.0)` to `/home/ord` and make the 
`export SCILAB_EXECUTABLE=~/scilab-6.1.0/bin/scilab-adv-cli`
Then run:
`import os`
`from metakernel.pexpect import which`
`which(os.environ['SCILAB_EXECUTABLE'])`
I get
`Out[3]: '/home/ord/scilab-6.1.0/bin/scilab-adv-cli'`
And all works!
But i get duplicated the `/scilab-6.1.0` folder in `/home/user` and `/opt` and it might have consequences.
What is the correct way to fix this?

**Comment by blink1073** [comment]
It looks like you had typos both times, first `export SCILAB_EXECUTABLE=/scilab-6.1.0/bin/scilab-adv-cli` (no opt), then `export SCILAB_EXECUTABLE=opt/scilab-6.1.0/bin/scilab-adv-cli` (no leading slash).

**Comment by ordonezt** [comment]
You are right, my bad! Thank you so much!!
