### ISSUE TITLE
Troubleshooting command badly formated

### ISSUE THREAD

**Issue by mxjeff** [Calysto/scilab_kernel#14]
There is a problem on the README, **Troubleshooting** command is not rendered.

**Comment by blink1073** [comment]
Hi @mxjeff, can you post a screenshot of what you're seeing?  It looks fine to me rendered on Github.  I'm not concerned with the rendering on PyPI, which is a very poor UX for maintainers.

**Comment by mxjeff** [comment]
Here what I see on firefox 60.6.3esr on Debian buster:

![screenshot](https://user-images.githubusercontent.com/2509872/58727635-2bf90400-83e5-11e9-9428-84795936ef96.png)

It looks like language type is not defined in rst source, but adding ``:: shell`` does not even seems to fix it, don't know what's happening here.

**Comment by blink1073** [comment]
Ahh, I see what you mean now, thank you.

**Comment by blink1073** [comment]
Tada:

![image](https://user-images.githubusercontent.com/2096628/58741053-ae2ffb00-83da-11e9-98e6-5399762b3fcb.png)
