### ISSUE TITLE
Launching kernel timeout (venv install)

### ISSUE THREAD

**Issue by mxjeff** [Calysto/scilab_kernel#16]
Trying to launch a scilab kernel I got `Timeout waiting for kernel_info reply`.

Running a kernel check, the output just wait on `Connecting…` without returning.
```sh
python3 -m scilab_kernel.check
Scilab kernel v0.9.10
Metakernel v0.24.0
Python v3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
Python path: /tmp/venv/bin/python3

Connecting to Scilab...
```
```sh
/usr/bin/scilab-cli -version
Scilab version "6.0.1.1518683525"
scilab-6.0.1
```
```sh
env | grep -i sci
SCILAB_EXECUTABLE=/usr/bin/scilab-cli
```
I'm trying scilab kernel wihtin a venv:
```sh
jupyter kernelspec list
Available kernels:
  python3    /tmp/venv/share/jupyter/kernels/python3
  scilab     /tmp/venv/share/jupyter/kernels/scilab

```
How can I debug that ?

Cheers

**Comment by blink1073** [comment]
Hmm, I exjust verified that Scilab 6.0 works "on my machine".  What is the output of `jupyter console --kernel=scilab`?

**Comment by mxjeff** [comment]
Hi,

Well I'm confused here, I can't reproduce exactly :|  
Now I managed to get a scilab prompt (running a console and even in a notebook), but then as soon as a launch the first command (a plain division), the prompt hangs there, not returning. In the notebook I got the "sand glass :hourglass_flowing_sand: " icon in my browser tab and the cells never change to executed state.

I'm sorry for this messy bug report, I guess I still have to narrow it down to have relevant info to move forward on this.

just for the record, here is what I've done on Debian buster (with latest updates):
```bash
sudo apt install scilab-cli
python3 -m venv /tmp/venv
. /tmp/venv/bin/activate
pip install jupyter scilab_kernel
export SCILAB_EXECUTABLE=/usr/bin/scilab-cli
jupyter console --kernel=scilab
```

**Comment by blink1073** [comment]
Were you able to interact with the `jupyter console`?

**Comment by mxjeff** [comment]
Well no, I got the prompt, but running a plain division `57/4` do not return.  
Hangs there
```jupyter
In [1]: 56/4
      :
```
Typing `^C` to recover the prompt I got this:
```
[…]/jupyter_console/ptshell.py:661: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
  warn('The kernel did not respond to an is_complete_request. '
```

I might have missed something or Debian/testing is buggy.  
I'll try to start over, maybe on Debian stable or CentOS.

**Comment by blink1073** [comment]
I have Linux Mint, but my wifi adapter stopped working.  I'll test it once my new adapter comes in :smile:

**Comment by blink1073** [comment]
Ugh, I was able to start the kernel on Linux Mint but not execute any cells; it just hangs.  I won't have bandwidth to look at this until after the JupyterLab 1.0 release.

**Comment by mxjeff** [comment]
It looks like it was related to a bug in the debian packaging (cf [#907607](https://bugs.debian.org/907607)).

The console is now working fine. I'll test it thoroughly and get back here to close the report if it's fine :)

**Comment by mxjeff** [comment]
Alright, it looks like it was indeed related to the debian bug.
I'm closing the report.
Thanks for your help @blink1073

**Comment by blink1073** [comment]
Glad you got sorted!
