### ISSUE TITLE
Doesn't work under JupyterLab, instead opens a separate Scilab window when called

### ISSUE THREAD

**Issue by fusion809** [Calysto/scilab_kernel#19]
Hi,

I've installed this kernel on Arch Linux with the [scilab-bin](https://aur.archlinux.org/packages/scilab-bin) AUR package installed and when I try to execute a cell in a JupyterLab notebook that is using the Scilab kernel a separate Scilab window is opened and the cell in JupyterLab freezes (never finishing the computation). Naturally, I installed this scilab_kernel using the command `pip install --user scilab_kernel`. 

Thanks for your time.

**Comment by blink1073** [comment]
Hi @fusion809, what does `which scilab-adv-cli` yield?

**Comment by fusion809** [comment]
/usr/local/bin/scilab-adv-cli. I should say I symlinked /opt/scilab/bin/* to /usr/local/bin, as scilab-bin installs all the binaries to /opt/scilab/bin.

**Comment by blink1073** [comment]
And when you run `scilab-adv-cli` from a terminal window it launches as a CLI and not as a graphical window?

**Comment by fusion809** [comment]
Yep, it launches as CLI.

**Comment by blink1073** [comment]
Do you have the `SCILAB_EXECUTABLE` variable set to something?

**Comment by fusion809** [comment]
No.

**Comment by fusion809** [comment]
Oh, I just started a new Jupyter Lab session and run a Scilab cell and it ran fine. So the issue seems resolved, so closing. Sorry for wasting your time.

**Comment by blink1073** [comment]
Ha, glad you got sorted!
