### ISSUE TITLE
Installation is normal, but when I try to run the notebook it never connects

### ISSUE THREAD

**Issue by IgorLim98** [Calysto/scilab_kernel#23]
I follow the instructions:

- pip install scilab kernel (ok)

- select a new scilab tab (ok)

In this new tab, the server never connects.
I am getting the following messages when i use "ipython qtconsole --kernel scilab"
![Capturar](https://user-images.githubusercontent.com/67347893/115614442-184e3380-a2c4-11eb-934e-e8cebcbe739d.PNG)

this one when i use " ipython console --kernel scilab"
![3](https://user-images.githubusercontent.com/67347893/115614879-990d2f80-a2c4-11eb-97e4-84dc38edc0d5.PNG)

and this one when i use "ipython notebook"
![1](https://user-images.githubusercontent.com/67347893/115615217-133db400-a2c5-11eb-8e70-3293fa1e5702.PNG)
This last one gets in a loop forever.

Please tell me if u can give more infor about how to fix it.  Thanks in advance.

**Comment by haniibrahim** [comment]
I had the same problem in GNU/Linux. Notebook could not connected to the scilab_kernel. 

> You can specify the path to your Scilab executable by creating a SCILAB_EXECUTABLE environmental variable. Use the scilab-adv-cli executable if using a Posix-like OS, and WScilex-cli.exe if using Windows.

helped.

**Comment by jbao161** [comment]
Go to Environment Variables. Create a user variable with name SCILAB_EXECUTABLE. Set the value to the path to the executable. Make sure to put quotation marks around the path if there are any space characters e.g. "C:\Program Files\scilab-6.1.1\bin\WScilex-cli.exe".
