### ISSUE TITLE
Kernel never connects

### ISSUE THREAD

**Issue by ghost** [Calysto/scilab_kernel#26]
Good day. 
I am running windows10, anaconda3,
I am unable to get jupyter notebook (6.4.12) to connect to the scilab kernel (I am able to connect to python kernel).
I followed instructions, and thought I was successful, but it just never connects... 

Kernel shows as available:
PS C:\Users\Tracey> jupyter kernelspec list
Available kernels:
  python3    C:\Users\Tracey\anaconda3\share\jupyter\kernels\python3
  scilab     C:\Users\Tracey\anaconda3\share\jupyter\kernels\scilab

But scilab executable not found:
PS C:\Users\Tracey> python -m scilab_kernel.check
Scilab kernel v0.9.10
Metakernel v0.29.3
Python v3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Python path: C:\Users\Tracey\anaconda3\python.exe

Connecting to Scilab...
Scilab connection established
Scilab Executable not found, please add to path or set"SCILAB_EXECUTABLE" environment variable

I then set SCILAB_EXECUTABLE environment variable, but nothing changed:
![image](https://user-images.githubusercontent.com/13378681/206692084-5528e19d-a46b-424d-82ec-412ee185fc87.png)

kernel.json file in the scilab kernel directory has the following contents:
{
    "argv": ["python",
             "-m", "scilab_kernel",
             "-f", "{connection_file}"],
    "display_name": "Scilab",
    "language": "scilab",
    "mimetype": "text/x-octave",
    "name": "scilab"
}

I copied WScilex-cli.exe into the anaconda3 directory, then instead get the following resulted: 
PS C:\Users\Tracey> python -m scilab_kernel.check
Scilab kernel v0.9.10
Metakernel v0.29.3
Python v3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Python path: C:\Users\Tracey\anaconda3\python.exe

Connecting to Scilab...
Scilab connection established
'true' is not recognized as an internal or external command,
operable program or batch file.
Command 'WScilex-cli -version -nwni || true' returned non-zero exit status 1.

Any suggestions as to what I am missing / doing wrong here?

**Comment by drillby** [comment]
Hi,
I had the same problem on Ubuntu, here's how I fixed it, hope it's the same fix on Windows.

So the problem is that scilab kernel can't find scilab executable in your env vars, this is becouse jupyter kernels don't have permisions to look into global env vars. You need to set it localy for the scilab kernel.

Open kernel.json in scilab kernel dir and add this line:
"env": {"SCILAB_EXECUTABLE":"path/to/scilab/executable"}

After this your notebook should not have problem with running.

Hope this helps.

**Comment by TraceyvH** [comment]
> Hi, I had the same problem on Ubuntu, here's how I fixed it, hope it's the same fix on Windows.
> 
> So the problem is that scilab kernel can't find scilab executable in your env vars, this is becouse jupyter kernels don't have permisions to look into global env vars. You need to set it localy for the scilab kernel.
> 
> Open kernel.json in scilab kernel dir and add this line: "env": {"SCILAB_EXECUTABLE":"path/to/scilab/executable"}
> 
> After this your notebook should not have problem with running.
> 
> Hope this helps.

Thanks for the suggestion, unfortunately this has not resolved my issue.

**Comment by apaeffgen** [comment]
I tried the same on MacOS, it is related to Issue No. 30. But i get errors and the kernel does not start up entirely.
Maybe it is a permission problem, but for testing purposes i also installed https://github.com/jupyterlab/jupyterlab-desktop.
And in this app the kernel works.
